---
title: "Interactive Graphics"
author: "Will Doyle
date: `r Sys.Date() `
---


```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(plotly)
library(leaflet)
```

```{r}

my_acs_key<-readLines("~/hod_datasci_keys/my_acs_key.txt",warn = FALSE)

acs_key<-my_acs_key

# Or just paste it here.
#acs_key<-"<your_acs_key_here>"

census_api_key(acs_key)

#v19 <- load_variables(2019, "acs5", cache = TRUE)

View(v19)

var_list<-paste0("B15002_",c("001",
                            "015",
                            "016",
                            "017",
                            "018",
                            "032",
                            "033",
                            "034",
                            "035"))

educ<-get_acs(geography="state",
                variables=var_list,
                output="wide",
                geometry=TRUE,
              keep_geo_vars = TRUE,
              year = 2019
                )

names(educ)<-tolower(names(educ))

educ<-educ%>%
  rename(State=name.x)

educ<-
  educ%>%
  group_by(State)%>%
  mutate(college_educ=((b15002_015e+
                         b15002_016e+
                         b15002_017e+
                         b15002_018e+
                         b15002_032e+
                         b15002_033e+
                         b15002_034e+
                         b15002_035e)/b15002_001e)*100)%>%
  select(State,college_educ,geometry)


```


```{r}

var_list<-paste0("B19001_",c("001",
                             "013",
                             "014",
                            "015",
                            "016",
                            "017"
                            ))

income<-get_acs(geography="state",
                variables=var_list,
                output="wide",
              year = 2019)

names(income)<-tolower(names(income))

income<-income%>%
  rename(State=name)

income<-income %>%
group_by(State) %>%
  mutate(
    income_75 = ((
      b19001_013e +
        b19001_014e +
        b19001_015e +
        b19001_016e +
        b19001_017e 
    ) / b19001_001e)*100
  )%>%
  select(State,income_75)


```


```{r}

var_list<-paste0("B27001_",c("001",
                             "004",
                             "007",
                            "010",
                            "013",
                            "016",
                            "019",
                            "022",
                            "025",
                            "028",
                            "032",
                            "035",
                            "038",
                            "041",
                            "044",
                            "047",
                            "041",
                            "050",
                            "053",
                            "056"                                                                             ))

health<-get_acs("state",
                variables=var_list,
                output="wide",
                year=2019
                )

names(health)<-tolower(names(health))


health<-health%>%
  rename(State=name)

health<-health %>%
  mutate(
    insured = ((
b27001_004e+
  b27001_007e+
  b27001_010e+
  b27001_013e+
  b27001_016e+
  b27001_019e+
  b27001_022e+
  b27001_025e+
  b27001_028e+
  b27001_032e+
  b27001_035e+
  b27001_038e+
  b27001_041e+
  b27001_044e+
  b27001_047e+
  b27001_041e+
  b27001_050e+
  +b27001_053e+
  b27001_056e
    ) / b27001_001e)*100
  )%>%
  select(State,insured)



```



```{r}
df<-educ%>%
  as_tibble()%>%
  left_join(income,by="State")%>%
  left_join(health,by="State")%>%
   mutate(`Pct w/ Bachelor's`=college_educ)%>%
  mutate(`Pct w/ Income>75k`=income_75)%>%
  mutate(`Pct w/ Health Insurance`=insured)%>%
  select(-income_75,-college_educ,-insured)

write_rds(df,"int_example.rds")
```

```{r}
df%>%
  mutate(State=fct_reorder(as_factor(State),`Pct w/ Bachelor's`))%>%
  ggplot(aes(x=State,
             y=`Pct w/ Bachelor's`,
             fill=`Pct w/ Bachelor's`,
             text=paste0(
               State,": ", round(`Pct w/ Bachelor's`,1)) 
                   ) )+
  geom_col()+
  scale_fill_fermenter(palette="YlGnBu")+
  coord_flip()+
  theme_minimal()->gg

ggplotly(gg,tooltip="text")
  
```

```{r}
df%>%
  ggplot(aes(y=`Pct w/ Income>75k`,
             x=`Pct w/ Bachelor's`,
             color=`Pct w/ Income>75k`,
             text=paste0(
               State,": ", 
               "<br>",
               "Pct w/ Bachelor's: ",
               round(`Pct w/ Bachelor's`,1) ,
               "<br>",
               "Pct w/ Income >75k: ",
               round(`Pct w/ Income>75k`,1)
                   )))+
  geom_point()+
  theme_minimal()+
  theme(legend.position = "none")->gg

ggplotly(gg,tooltip="text")
  
```


```{r}
df2<-educ%>%
  left_join(income)%>%
  left_join(health)
```


```{r}
df2%>%
  leaflet()%>%
  addPolygons()

```

```{r}

df2%>%
    st_transform(crs = "+init=epsg:4326")%>%
  leaflet()%>%
  addPolygons()

```


```{r}

df2%>%
  filter(!(State%in%c("Alaska","Hawaii")))%>%
    st_transform(crs = "+init=epsg:4326")%>%
  leaflet()%>%
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons()
  

```


```{r}

pal <- colorQuantile(palette = "viridis", 
                     domain = df2$college_educ, n = 10)
```


```{r}


df2%>%
  filter(!(State%in%c("Alaska","Hawaii")))%>%
    st_transform(crs = "+init=epsg:4326")%>%
  leaflet()%>%
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons(popup = ~ zip, 
                stroke = FALSE,
                smoothFactor = 0,
                fillOpacity = 0.7,
                color = ~ pal(college_educ)) 

```


```{r}

df2%>%
  filter(!(State%in%c("Alaska","Hawaii")))%>%
    st_transform(crs = "+init=epsg:4326")%>%
  leaflet()%>%
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons(popup = ~ zip, 
                stroke = FALSE,
                smoothFactor = 0,
                fillOpacity = 0.7,
                color = ~ pal(college_educ)) %>%
 addLegend("bottomright", 
              pal = pal, 
              values = ~ college_educ,
              title = "Percent with a bachelor's degree",
              opacity = 1)
```

