---
title: "01-Assignment"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Your first commit: hello_world.Rmd

.Rmd files will be the only file format we work in this class. .Rmd files contain three basic elements:

1. Script that can be interpreted by R. 
2. Output generated by R, including tables and figures.  
3. Text that can be read by humans. 

From a .Rmd file you can generate html documents, pdf documents, word documents, slides . . . lots of stuff. All class notes will be in .Rmd. All assignments will be turned in as .Rmd files, and your final project? You guessed it, .Rmd. 

For your first assignment, I want you to create a file called `01-assignment_<lastname>.Rmd` in your github repo in the assignments folder. It should contain the following elements:

1. A sentence that says "Hello, World"
2. R output that summarizes one of the variables in the `sc_debt.Rds` dataset

Submit it under assignment 1, using the format `01-assignment_<lastname>.Rmd`. All assignments should be turned in using this format. Since my last name is Doyle, I would use `01-assignment_doyle.Rmd` as my file name. Unless your name is also Doyle, you should use a different name. 


*Stretch Items*

If you have extra time, you can do the following:

1. Calculate the average debt level for individuals at the most selective colleges, then compare that with individuals at the least selective colleges in the dataset. 
2. Find a way to determine whether colleges with very high SAT scores tend to be larger or smaller than colleges with low SAT scores. 
3. Plot the relationship between cost and debt. What do you see? Does this surprise you? 
4. Now, provide separate plots for cost and debt by control of the institution. 
