---
title: "Sports APIs"
author: "Will Doyle"
date: "October 1, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Order of libraries is important
library(tidyverse)
library(devtools)
#devtools::install_github(devtools::install_github("MySportsFeeds/mysportsfeeds-r"))
library(mysportsfeedsR)
```

```{r}
sf_username<-readLines("sportsfeeds_username.txt")
sf_password<-readLines("sportsfeeds_pasword.txt")
```

```{r}


.MySportsFeedsEnv<-list()
.MySportsFeedsEnv$data$username <-sf_username
.MySportsFeedsEnv$data$password <- sf_password

nfl_season_stats <- msf_get_results(league='nfl',season='2015-2016-regular',feed='cumulative_player_stats')        
```
```{r}
nfl_int_data<-data.frame(
nfl_season_stats$api_json$cumulativeplayerstats$playerstatsentry$player.ID,
nfl_season_stats$api_json$cumulativeplayerstats$playerstatsentry$player.LastName,
nfl_season_stats$api_json$cumulativeplayerstats$playerstatsentry$player.FirstName,
nfl_season_stats$api_json$cumulativeplayerstats$playerstatsentry$`stats.Interceptions.#text`)

names(nfl_int_data)<-c("player_id","lastname","firstname","interceptions")

## This accesses week by week player-level data
## Note: don't know why so many players have "2"

nfl_game_stats <- msf_get_results(league='nfl',season='2015-2016-regular',feed='player_gamelogs',params = list(team="sf"))

nfl_run_data<-data.frame(
nfl_game_stats$api_json$playergamelogs$gamelogs$game.id,  
nfl_game_stats$api_json$playergamelogs$gamelogs$player.ID,
nfl_game_stats$api_json$playergamelogs$gamelogs$player.LastName,
nfl_game_stats$api_json$playergamelogs$gamelogs$player.FirstName,
nfl_game_stats$api_json$playergamelogs$gamelogs$`stats.RushYards.#text`)

  names(nfl_run_data)<-c("game_id","player_id","lastname","firstname","run_yards")

  nfl_run_data$run_yards<-as.numeric(nfl_run_data$run_yards)

  nfl_run_data<-nfl_run_data%>%filter(run_yards>2)
  nfl_run_data<-nfl_run_data%>%arrange(-run_yards)
  
nfl_team_stats<- msf_get_results(league='nfl',season='2015-2016-regular',feed='team_gamelogs',params = list(team="sf"))

nfl_team_data<-data.frame(
  nfl_team_stats$api_json$teamgamelogs$gamelogs$game.id,
  nfl_team_stats$api_json$teamgamelogs$gamelogs$game.date,
  nfl_team_stats$api_json$teamgamelogs$gamelogs$`stats.RushYards.#text`)

names(nfl_team_data)<-c("gameid","game_date","rush_yards")

nfl_team_data$rush_yards<-as.numeric(as.character(nfl_team_data$rush_yards))

    
  
# compare with: https://www.pro-football-reference.com/years/2015/leaders.htm

```


```{r}

nhl_data<-msf_get_results(league='nhl',season='2015-2016-regular',feed='team_gamelogs',params=list(team=list("nashville-predators")), verbose = TRUE,version=1.1)        

team_data<-data.frame(
nhl_data$api_json$teamgamelogs$gamelogs$`stats.GoalsFor.#text`,
nhl_data$api_json$teamgamelogs$gamelogs$`stats.GoalsAgainst.#text`,
nhl_data$api_json$teamgamelogs$gamelogs$`stats.Wins.#text`,
nhl_data$api_json$teamgamelogs$gamelogs$`stats.Powerplays.#text`)

names(team_data)<-c("goals_for","goals_against","win","powerplays")

team_data$goals_for<-as.numeric(team_data$goals_for)
team_data$goals_against<-as.numeric(team_data$goals_against)
team_data$win<-as.numeric(team_data$win)
team_data$powerplays<-as.numeric(team_data$powerplays)


gg<-ggplot(team_data,aes(x=powerplays,y=goals_for))
gg<-gg+geom_jitter(width = .1)
gg
```

