---
title: "Nice Looking Tables in R Markdown"
author: "Will Doyle"
date: "11/29/2018"
output:
  html_document: default
  word_document: default
---

```{r}
library(knitr)
library(stargazer)
library(tidyverse)
```


## Option 1: Kable
Let's say we want to provide a table of median home value as a function of the percent of the population who are college grads. 
```{r}
load("../lessons/pd.Rdata")

pd%>%mutate(`College Graduate Quintile`=ntile(coll_grad_pc,n=5))%>%
  group_by(`College Graduate Quintile`)%>%
  summarize(`Mean Home Value`=mean(median_home_val))%>%
  mutate(`Mean Home Value`=prettyNum(round(`Mean Home Value`,0),
         big.mark=","))%>%
  kable()
```

## Stargazer
If you want to report results from a regression, then stargazer is your friend.
```{r,results='asis'}

mod1<-lm(log(median_home_val)~
           coll_grad_pc+
           travel_time+
           per_capita_inc, 
         data=pd)

stargazer(mod1,type="html",
          covariate.labels = c("% Coll Grads","Travel Time","Per Capita Income") )
```


